variable "tenancy_ocid" {}
variable "compartment_ocid" {}
variable "availability_domain" {}
variable "jenkins_version" {}
variable "jenkins_password" {}
variable "master_display_name" {}
variable "subnet_id" {}
variable "instance_shape" {}
variable "ssh_public_key" {}
variable "ssh_private_key" {}
variable "image_ocid" {}
variable "http_port" {}
variable "plugins" {}
variable "instance_user" {}